### PR TITLE
Add create_newlines to replace BR and P by 1, resp. 2 newlines

### LINKED ISSUE #25: Option to turn <br> tags into a newline
`<br>` tags could be turned into newlines and something similar done for `<p>`.

See reviews at http://cpanratings.perl.org/dist/HTML-Strip

### PR DESCRIPTION
**Pull request by choroba**
Fixes #25.

### CODE REVIEW

**Comment by choroba** [comment]
Greetings from the Pull Request Club.

**Comment by oalders** [comment]
Nice! Closes an issue from 6 years ago. Closing and re-opening to kick off a CI build.

**Comment by oalders** [comment]
Looks like it needs tidying and possible `br` added to the stopwords file. https://github.com/oalders/html-restrict/actions/runs/4623161825/jobs/8176686783?pr=46

**Comment by choroba** [comment]
Tidied, stopwords updated. If you find it OK, ping me to squash.

**Comment by oalders** [comment]
Thanks, @choroba!

**Pull request merged**
